all: calibration.cpp
	g++ calibration.cpp -I/usr/include/opencv4 -o calibration -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core

